import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";
import { partnerships } from "@/lib/qualification";
export const metadata: Metadata = { alternates: { canonical: "/" }, openGraph: { url: "/", title: "Buyology Business | Become a Stockist & Retail Partner", description: "Bring certified refurbished technology to your market with Buyology." } };
export default function Home() {
 const schema = { "@context": "https://schema.org", "@type": "Organization", name: "Buyology", url: "https://business.buyology.online", logo: "https://business.buyology.online/logo-light.png", sameAs: ["https://buyology.online", "https://instagram.com/buyology.online"], description: "Certified refurbished technology and stockist, retail and B2B distribution partnerships.", contactPoint: { "@type": "ContactPoint", email: "support@buyology.online", contactType: "business enquiries" } };
 return <><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(schema).replace(/</g, "\u003c") }} />
 <section className="hero"><div className="container hero-grid"><div className="hero-copy"><p className="eyebrow">BUYOLOGY PARTNER PROGRAMME</p><h1>Good technology.<br />Great potential.<br /><span>Your next chapter.</span></h1><p className="hero-description">Bring certified refurbished laptops and tablets to your market. Build a local technology business with Buyology as your partner.</p><div className="hero-actions"><Link className="button" href="/become-partner/">Become a partner</Link><a className="text-link" href="#why-buyology">Discover the opportunity</a></div><p className="hero-note">For stockists, retailers and B2B distributors.</p></div><div className="hero-visual"><div className="visual-label">A SECOND LIFE FOR TECH.<br /><strong>A NEW OPPORTUNITY FOR YOU.</strong></div><Image src="/partner-laptop.jpg" alt="Laptop representing the refurbished technology available through Buyology" width={1200} height={900} priority /><div className="visual-caption"><span>BUY THE WHY</span><span>Laptops & tablets</span></div></div></div></section>
 <div className="brand-strip"><div className="container"><span>ONE BRAND. MORE WAYS TO GROW.</span><p>Local inventory</p><p>Retail opportunity</p><p>Business distribution</p></div></div>
 <section id="why-buyology" className="section container"><div className="section-heading"><p className="eyebrow">WHY BUYOLOGY</p><h2>Technology with a purpose.<br />Partnership with potential.</h2><p>Buyology gives technology a second life through inspected and tested refurbished devices. Our partner programme brings that approach closer to customers through businesses with local knowledge.</p></div><div className="benefit-grid">{[
 ["01", "A clear product focus", "Build around refurbished laptops and tablets: useful technology for work, learning and everyday life."],
 ["02", "Your local advantage", "Connect Buyology’s online offering with your customer relationships, local inventory and fulfilment capability."],
 ["03", "More routes to market", "Choose a stockist, retail or B2B distribution partnership that fits the business you already operate."],
 ["04", "A longer view", "Start with a focused local operation and discuss larger territory responsibility as the partnership develops."],
 ].map(([n,title,body])=><article key={n} className="benefit"><span>{n}</span><h3>{title}</h3><p>{body}</p></article>)}</div></section>
 <section className="partnership-section"><div className="container"><div className="section-heading"><p className="eyebrow">FIND YOUR FIT</p><h2>One ambition.<br />Your way to partner.</h2><p>Tell us where you want to take your business. Choose your preferred partnership when you apply.</p></div><div className="partnership-grid">{partnerships.map(p=><article className="partnership-card" key={p.value}><span className="card-number">{p.number}</span><h3>{p.title}</h3><p>{p.description}.</p><Link href={`/become-partner/?interest=${p.value}`}>Explore this partnership</Link></article>)}</div></div></section>
 <section className="section container readiness"><div><p className="eyebrow">BUILT FOR COMMITTED PARTNERS</p><h2>Ready to build<br />something together?</h2><p>We’re looking for partners with the business capability, investment capacity and sales ambition to hold and grow local inventory.</p><Link className="button" href="/become-partner/">Start your application</Link></div><div className="readiness-panel"><div><strong>USD 50,000–100,000</strong><p>Approximate initial inventory investment sought. Other investment ranges are included in the application.</p></div><div><strong>50 units / month</strong><p>Initial sales capability, with an ambition to grow to 100+ laptops and tablets per month.</p></div><div><strong>5 simple steps</strong><p>Share your business profile, capabilities and preferred partnership. Qualifying profiles move to a detailed discussion and MOU meeting.</p></div></div></section>
 <section className="closing"><div className="container"><p className="eyebrow">THE NEXT CHAPTER STARTS HERE</p><h2>Let’s put good technology<br />in more hands.</h2><Link className="button" href="/become-partner/">Become a Buyology partner</Link></div></section>
 </>;
}
